[config]

# log_dir = "logs"
log_level = "debug"
# dest_dir = "dstFolder"
# db_name = "mlm-db"
# thumbnail_dir = "thumbnails"

[directories]

 [directories.test]

 path = "TestFolder"
 # Possible values for 'move_type' are 'keep', 'managed', 'flatten', and 'none'
 move_type = "flatten"
 get_md5 = "true"
# ignored_filetypes = ["CR2"]